/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDashboardDataRouteImport } from './routes/api/dashboard-data'
import { Route as ApiConversationRouteImport } from './routes/api/conversation'
import { Route as ApiAuthRouteImport } from './routes/api/auth'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardDataRoute = ApiDashboardDataRouteImport.update({
  id: '/api/dashboard-data',
  path: '/api/dashboard-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationRoute = ApiConversationRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/dashboard-data': typeof ApiDashboardDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/dashboard-data': typeof ApiDashboardDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/dashboard-data': typeof ApiDashboardDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/auth'
    | '/api/conversation'
    | '/api/dashboard-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth'
    | '/api/conversation'
    | '/api/dashboard-data'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/auth'
    | '/api/conversation'
    | '/api/dashboard-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiConversationRoute: typeof ApiConversationRoute
  ApiDashboardDataRoute: typeof ApiDashboardDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard-data': {
      id: '/api/dashboard-data'
      path: '/api/dashboard-data'
      fullPath: '/api/dashboard-data'
      preLoaderRoute: typeof ApiDashboardDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiConversationRoute: ApiConversationRoute,
  ApiDashboardDataRoute: ApiDashboardDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
